### ISSUE TITLE
Is this working with ENet?

### ISSUE THREAD

**Issue by neatek** [javawork/ENet-CSharp-Unity-Example#2]
Hello,

Is this working with http://enet.bespin.org/Downloads.html ? v1.3.15
i did Linux C++ server using this C library...

When i trying connect by this Example to my server it wrote:
```
Connecting
UnityEngine.Debug:Log(Object)
```
I change in SceneManager.cs 
```
const string ip = "95.216.189.x";
const ushort port = 7777;
```
And nothing else

When i send package by my test client on C++ its working(with remote client connection), but not in Unity using already compiled enet.dll. Here is compiled x86 and x86_64 libs for Windows from (http://enet.bespin.org/Downloads.html) : https://drive.google.com/file/d/1NFvAg1n-IGtf2TsDEv5bKBSliC64zah6/view?usp=sharing

Also when i trying to connect these libs compiled in Unity it wrote me: 
`EntryPointNotFoundException 😕`

Can you give me advice or help with this?
telegram @neatek

**Comment by javawork** [comment]
This works only with https://github.com/nxrighthere/ENet-CSharp, not enet C project.
